# Generated by Django 5.2 on 2025-04-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlbdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='old_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
