# Generated by Django 5.2 on 2025-04-23 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mlb_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("old_id", models.CharField(max_length=10, null=True)),
                ("name", models.CharField(max_length=33)),
                ("league", models.CharField(max_length=10)),
                ("year_founded", models.IntegerField()),
                ("most_recent_year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TeamSeason",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("wins", models.IntegerField(null=True)),
                ("losses", models.IntegerField(null=True)),
                ("games_played", models.IntegerField(null=True)),
                ("rank", models.IntegerField(null=True)),
                ("total_attendance", models.IntegerField(null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="mlb_data.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_season",
                "unique_together": {("team", "year")},
            },
        ),
        migrations.AddField(
            model_name="player",
            name="team_seasons",
            field=models.ManyToManyField(to="mlb_data.teamseason"),
        ),
    ]
